### ISSUE TITLE
cloudflare workersで環境変数を扱う

### ISSUE THREAD

**Issue by NAORIKU** [NAORIKU/manabi#32]
cloudflare workersで実行しているスクリプトで環境変数を取り扱う方法を把握したかったのでメモします。

> [公式ドキュメント](https://developers.cloudflare.com/workers/platform/environment-variables#environment-variables-via-wrangler)に一通り書いてあります。

サクッとやるなら、`wrangler.toml`に記述する方法が良さそうとは思いつつ、
最終的には、GitHub Actionsで[wrangler-action](https://github.com/cloudflare/wrangler-action)を活用したワークフローを構築するため、GitHubレポジトリのSecretsに定義した値をデプロイ時に受け渡すのがベターかなと考えています。

## [`wrangler.toml`](https://developers.cloudflare.com/workers/platform/environment-variables#environment-variables-via-wrangler)に記述する

```yaml
[vars]
API_TOKEN = "example_dev_token"
STRIPE_TOKEN = "pk_xyz1234_test"

[env.production.vars]
API_TOKEN = "example_production_token"
STRIPE_TOKEN = "pk_xyz1234"
```

## [`wrangler-action`](https://github.com/cloudflare/wrangler-action#configuration)の機能を使う

> Worker secrets can be optionally passed as a new line deliminated string of names in secrets. Each secret name must match an environment variable name specified in the env attribute. Creates or replaces the value for the Worker secret using the wrangler secret put command.

```yaml
jobs:
  deploy:
    steps:
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        secrets: |
            SECRET1
            SECRET2
      env:
        SECRET1: ${{ secrets.SECRET1 }}
        SECRET2: ${{ secrets.SECRET2 }}

```
