### ISSUE TITLE
wrangler-actionでcloudflare workersの環境変数を扱う

### ISSUE THREAD

**Issue by NAORIKU** [NAORIKU/manabi#33]
cloudflare workersで社内向けに、あまりアクセス頻度は多くないが高度なタスクを実行できる管理ツールを作成する機会がありました。

例えば、API Tokenなどの特定の権限を持つシークレットキーを管理する必要があったので、github repositoryのsecretsで管理してcloudflare workers上で実行するサービスで扱えるようにしました。

管理ツールは、GitHub ActionsをCIとしてwrangler-actionというActionを活用してデプロイしています。

このAction実行時に、github repositoryで管理されているsecretsをcloudflareに登録してくれる機能があったので活用してみました。

`GitHub上で登録したsecrets`
<img width="807" alt="スクリーンショット 2022-02-10 20 40 51" src="https://user-images.githubusercontent.com/50829476/153401852-6f26ed92-ab1f-4817-bdbb-49439c709bea.png">

`Github Action`

```yaml
jobs:
  deploy:
    steps:
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        secrets: |
            SECRET1
            SECRET2
      env:
        SECRET1: ${{ secrets.SECRET1 }}
        SECRET2: ${{ secrets.SECRET2 }}
```

`実行スクリプト`

> 実験として、ping打ったらJSONに値を返すようにした 💣 

```js
router.get("/ping", async () => {
  const response = {
    "pong": "hi!", 
    "SECRET1": SECRET1, 
    "SECRET2": SECRET2 
  }
  return new Response(JSON.stringify(response), {
    headers: {
      "Content-Type": "application/json"
    }
  })
});
```

`結果`

> おお〜！ちゃんとgithub repository上の環境変数がサービス上で取り扱いできている！

```
➜  ~ curl https://xxxxxx.yyyyyyy.workers.dev/ping
{"pong":"hi!","SECRET1":"開けゴマ！","SECRET2":"fonzie!"}
```
